![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [87]:
# Import necessary packages
import pandas as pd
import numpy as np

# Begin coding here ...
# Use as many cells as you like

In [88]:
# What are the dates of the earliest and most recent reviews? Store these values as two separate variables with your preferred names.

review_df = pd.read_csv('data/airbnb_last_review.tsv', sep='\t', )

rooms_df = pd.read_excel('data/airbnb_room_type.xlsx')

price_df = pd.read_csv('data/airbnb_price.csv')

# Join the three data frames together into one
listings = pd.merge(price_df, rooms_df, on='listing_id')
listings = pd.merge(listings, review_df, on='listing_id')

In [89]:
# What are the dates of the earliest and most recent reviews?
# To use a function like max()/min() on last_review date column, it needs to be converted to datetime type
listings['last_review_date'] = pd.to_datetime(listings['last_review'], format='%B %d %Y')
first_reviewed = listings['last_review_date'].min()
last_reviewed = listings['last_review_date'].max()
print(first_reviewed, last_reviewed)

2019-01-01 00:00:00 2019-07-09 00:00:00

In [90]:
# How many of the listings are private rooms? Save this into any variable.

#check unique values and what descrepancies may exist in the df entries
for value in listings['room_type'].unique():
    print(value)

Entire home/apt
private room
Private room
entire home/apt
PRIVATE ROOM
shared room
ENTIRE HOME/APT
Shared room
SHARED ROOM

In [91]:
#are there duplicated values?
duplicates = listings.duplicated()
print(duplicates)

0        False
1        False
2        False
3        False
4        False
         ...
25204    False
25205    False
25206    False
25207    False
25208    False
Length: 25209, dtype: bool

In [92]:
listings['room_type'] = listings['room_type'].str.lower()
listings['room_type'].value_counts()

entire home/apt    13266
private room       11356
shared room          587
Name: room_type, dtype: int64

In [93]:
private_rooms = listings.query('room_type == "private room"').count().iloc[0]

print (f'There are {private_rooms} listings with private rooms')

There are 11356 listings with private rooms

In [94]:
listings['price'] = listings['price'].astype('str')
listings['price'] = listings['price'].str.strip(' dollars')
listings['price'] = listings['price'].astype('int')

assert listings['price'].dtype == 'int'

average_price = listings['price'].mean().round(2)

print(f'The average listing price is {average_price}')

The average listing price is 141.78

In [95]:
# Combine the new variables into one DataFrame called review_dates with four columns in the following order: first_reviewed, last_reviewed, nb_private_rooms, and avg_price. The DataFrame should only contain one row of values.

# Create a dictionary containing the variables as values
values_dict = {
    "first_reviewed": first_reviewed,
    "last_reviewed": last_reviewed,
    "nb_private_rooms": private_rooms,
    "avg_price": average_price}

# Create a DataFrame from the dictionary with a single row
review_dates = pd.DataFrame(values_dict, index=[0])

# Display the DataFrame
review_dates.head()

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78